export const fonts = {
  extraLight: 'Nunito-ExtraLight',
  extraLightItalic: 'Nunito-ExtraLightItalic',
  light: 'Nunito-Light',
  lightItalic: 'Nunito-LightItalic',
  regular: 'Nunito-Regular',
  regularItalic: 'Nunito-Italic',
  medium: 'Nunito-Medium',
  mediumItalic: 'Nunito-MediumItalic',
  bold: 'Nunito-Bold',
  boldItalic: 'Nunito-BoldItalic',
  semiBold: 'Nunito-SemiBold',
  semiBoldItalic: 'Nunito-SemiBoldItalic',
  extraBold: 'Nunito-ExtraBold',
  extraBoldItalic: 'Nunito-ExtraBoldItalic',
  black: 'Nunito-Black',
  blackItalic: 'Nunito-BlackItalic',
  extraBlack: 'Nunito-Black',
  extraBlackItalic: 'Nunito-BlackItalic',
};
